### ISSUE TITLE
can't use '.'(dot) in 'configName' option

### ISSUE THREAD

**Issue by EladBezalel** [js-cli/js-liftoff#100] opened 2019-03-25 16:02 UTC
When creating a new Liftoff instance and passing a `configName` you can't use `.` as part of it.

I want to have a cli named `dcm` and it's config file to be `dcm.config.{ext}`

```js
import Liftoff from 'liftoff';
import { jsVariants } from 'interpret';

const Dcm = new Liftoff({
  name: 'dcm',
  configName: 'dcm.config',
  extensions: jsVariants
});

Dcm.prepare({}, env =>
  Dcm.execute(env, () => {
    const config = env.configPath ? require(env.configPath).default : undefined;
    // do something with config
  })
)
```

at this point when requiring the config the *registered loaders* doesn't seem to run properly, when removing the `.` from the name or having es5 code syntax in the config file, it works.

**Comment by sttk** [comment] 2019-03-26 14:11
@EladBezalel On `node --experimental-modules`, the above code outputs error message: `UnhandledPromiseRejectionWarning: ReferenceError: require is not defined`.

How about using `import()` instead of `require()`?

**Comment by EladBezalel** [comment] 2019-03-28 14:16
It doesn't seem to be related to `require` nor `import` 

How is `--experimental-modules` related to this issue?

For me it seems as somewhere along the way some package is splitting by `.` and loses context of the registered loaders for that file type.

**Comment by sttk** [comment] 2019-03-29 12:26
I'm sorry if I misunderstood. I thought this issue that the above code failed to run at requiring, and tried it as follows. (About `--experimental-modules` it was for explanation of my execution setting.)

```sh
$ cat dcm.config.js 
exports.hello = 'Hello'
$ cat dcm.mjs
import Liftoff from 'liftoff '
import interpret from 'interpret'
const Dcm = new Liftoff({
  name: 'dcm',
  configName: 'dcm.config',
  extensions: interpret.jsVariants,
})
Dcm.prepare({}, env =>
  Dcm.execute(env, async () => {
    const cfg = env.configPath ? require(env.configPath) : undefined
    console.log(cfg)
    console.log(env)
  })
)
$ node --experimental-modules dcm.mjs
(node:24388) ExperimentalWarning: The ESM module loader is experimental.
(node:24388) UnhandledPromiseRejectionWarning: ReferenceError: require is not defined
　〜
$ vi dcm.mjs
   〜
    const cfg = env.configPath ? require(env.configPath) : undefined;
    → const cfg = env.configPath ? await import(env.configPath) : undefined;
　〜
$ node --experimental-modules dcm.mjs
(node:24423) ExperimentalWarning: The ESM module loader is experimental.
[Module] { default: { hello: 'Hello' } }
{ cwd: '/path/to/issue100',
  require: [],
  configNameSearch:
   [ 'dcm.config.js',
     'dcm.config.babel.js',
     'dcm.config.babel.ts',
     'dcm.config.buble.js',
     'dcm.config.cirru',
     'dcm.config.cjsx',
     'dcm.config.co',
     'dcm.config.coffee',
     'dcm.config.coffee.md',
     'dcm.config.eg',
     'dcm.config.esm.js',
     'dcm.config.iced',
     'dcm.config.iced.md',
     'dcm.config.jsx',
     'dcm.config.litcoffee',
     'dcm.config.liticed',
     'dcm.config.ls',
     'dcm.config.ts',
     'dcm.config.tsx',
     'dcm.config.wisp' ],
  configPath: '/path/to/issue100/dcm.config.js',
  configBase: '/path/to/issue100',
  modulePath: undefined,
  modulePackage: {},
  configFiles: {} }
$
```

What result do you mention improper? Could you show me any output of running?

**Comment by EladBezalel** [comment] 2019-03-29 21:52
I think I have forgot to mention my config file is in typescript

```typescript
export default {
  a: 'a'
}
```

By saying that the registered loaders aren't working I meant that when I have `.` in the config file it doesn't transpiles the file, even with Babel just
It works when I remove the dot from the config name.

I hope that's clearer

**Comment by sttk** [comment] 2019-04-05 13:46
@EladBezalel is this what you want? If this is different, please post your execution example.

```
$ node -v
v10.15.3
$ npm -v
6.4.1
$ cat dcm.js
import Liftoff from 'liftoff';
import { jsVariants } from 'interpret';
const Dcm = new Liftoff({
  name: 'dcm',
  configName: 'dcm.config',
  extensions: jsVariants
});
Dcm.prepare({}, env =>
  Dcm.execute(env, () => {
    const config = env.configPath ? require(env.configPath).default : undefined;
    console.log(config);
  })
)
$ cat dcm.config.ts 
export default {
  a: 'a'
}
$ npm i liftoff interpret ts-node babel-cli babel-preset-env
$ echo '{ "presets": ["env"] }' > .babelrc
$ npx babel-node dcm.js
{ a: 'a' }
$
```

**Comment by EladBezalel** [comment] 2019-04-07 09:03
So your example is working, though when i try to create a cli tool out of it it seems to fail..

I replicated it [here on glitch](https://glitch.com/edit/#!/emerald-screen?path=index.ts:7:14)

Once i move the Liftoff preparation and execution inside a function it fails with the dot in the name..

Thanks for looking into it

**Comment by sttk** [comment] 2019-04-07 14:48
@EladBezalel  Thanks for your code. I could reproduce this issue.

The cause of this issue is [rechoir#37](https://github.com/gulpjs/rechoir/pull/37) and this was already fixed but liftoff has not update it yet.

I've sent a [PR](https://github.com/js-cli/js-liftoff/pull/102) and this issue will be fixed by it.

**Comment by EladBezalel** [comment] 2019-04-07 15:14
That's awesome, thanks for looking into it. love your project, keep up the good work :)

**Closed** 2019-04-20 16:33 UTC
